/*
DesignBuilder's default plant templates are configured with primary
(headered) pumping only. When a primary-secondary configuration is
built manually — with dedicated, non-headered pumps on the primary
side — DesignBuilder does not reliably stage those pumps on/off in
sync with the equipment they serve. This script post-processes the
EnergyPlus IDF file generated by DesignBuilder and adds an
EnergyManagementSystem (EMS) program that turns each dedicated pump
on or off based on the operating status of its associated plant
equipment (boiler, chiller, heat pump, or cooling tower).
*/
using DB.Extensibility.Contracts;
using EpNet;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime;
using System.Text.RegularExpressions;
using System.Windows.Forms;

namespace DB.Extensibility.Scripts
{
    public class DedicatedPumpsStaging : ScriptBase, IScript
    {
        public override void BeforeEnergySimulation()
        {
            try
            {
                IdfReader idf = new IdfReader(ApiEnvironment.EnergyPlusInputIdfPath, ApiEnvironment.EnergyPlusInputIddPath);
                CreateEMS(idf);
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message, "Unrecognized Equipment", MessageBoxButtons.OK, MessageBoxIcon.Error);
                throw;
            }

        }
        public void CreateEMS(IdfReader idf)
        {
            Dictionary<string, int> plantLoops = new Dictionary<string, int>();
            List<string> unrecognizedBranches = new List<string>();
            List<IdfObject> branchs = idf["Branch"];
            string linesEMS = @"EnergyManagementSystem:ProgramCallingManager,
Control_Pumps_Manager,
InsideHVACSystemIterationLoop,
Control_Pumps;

EnergyManagementSystem:Program,
Control_Pumps,
";
            foreach (IdfObject branch in branchs)
            {
                if (branch["Component 1 Object Type"].Value.Contains("Pump:"))
                {
                    if (branch.Count == 10) // 10: number of available fields in the object. Name (1 field) + Pressure Curve (1 field) + 2 components [pump + plant equipment] (4 fields x component) = 10 fields;
                    {
                        string pumpName = branch["Component 1 Name"];
                        string pumpType = branch["Component 1 Object Type"];
                        string plantEquipmentName = branch["Component 2 Name"];
                        string plantEquipmentType = branch["Component 2 Object Type"];
                        string nameSensor = CreateSensor(idf, plantEquipmentName, plantEquipmentType);
                        string nameActuator = CreateActuator(idf, pumpName, pumpType);
                        linesEMS += String.Format(@"IF {0} > 0.0,
SET {1} = 1.0,
ELSE,
SET {1} = 0.0,
ENDIF,", nameSensor, nameActuator);
                        string pumpBranchName = branch["Name"];
                        string plantLoopName;
                        if (TryGetPlantLoopName(pumpBranchName, pumpName, out plantLoopName))
                        {
                            if (!plantLoops.ContainsKey(plantLoopName))
                            {
                                plantLoops[plantLoopName] = 1;
                            }
                            else
                            {
                                plantLoops[plantLoopName]++;
                            }
                        }
                        else
                        {
                            unrecognizedBranches.Add(pumpBranchName);
                        }
                    }
                }
            }
            if (plantLoops.Count == 0 && unrecognizedBranches.Count == 0)
            {
                MessageBox.Show("No dedicated pump configuration was found in this model. No EMS objects were created.",
                    "EMS Summary", MessageBoxButtons.OK, MessageBoxIcon.Information);
                return;
            }
            idf.Load(linesEMS.TrimEnd(',') + ";");
            idf.Save();
            ShowSummary(plantLoops, unrecognizedBranches);
        }
        private bool TryGetPlantLoopName(string branchName, string pumpName, out string plantLoopName)
        {
            string pattern = @"\A" + Regex.Escape(pumpName) + @"\s+(.+?)\s+Supply Side Branch$";
            Match match = Regex.Match(branchName, pattern);
            if (match.Success)
            {
                plantLoopName = match.Groups[1].Value;
                return true;
            }
            else
            {
                plantLoopName = null;
                return false;
            }
        }
        private void ShowSummary(Dictionary<string, int> plantLoops, List<string> unrecognizedBranches)
        {
            List<string> lines = new List<string>();
            lines.Add("EMS was applied in the next plants: ");
            lines.Add("");
            foreach(KeyValuePair<string, int> kvp in plantLoops)
            {
                lines.Add(String.Format("- {0}: {1} pumps",kvp.Key, kvp.Value));
            }
            MessageBoxIcon icon = MessageBoxIcon.Information;
            if (unrecognizedBranches.Count > 0)
            {
                lines.Add("");
                lines.Add("WARNING: The plant could not be identified for the following branches because their names do not match the expected format. The EMS was still generated successfully for these branches; however, it is recommended to manually verify which plant they belong to:");
                foreach (string name in unrecognizedBranches)
                {
                    lines.Add("  - " + name);
                }
                icon = MessageBoxIcon.Warning;
            }
            MessageBox.Show(string.Join(Environment.NewLine, lines), "EMS Summary", MessageBoxButtons.OK, icon);
        }
        public string CreateSensor(IdfReader idf, string plantEquipmentName, string plantEquipmentType)
        {
            string outputVariable = GetOutputVariable(plantEquipmentType);
            string nameSensor = "DemandRate_" + plantEquipmentName.Replace(" ", "");
            string sensor = @"EnergyManagementSystem:Sensor,
{0},
{1},
{2};";
            idf.Load(String.Format(sensor, nameSensor, plantEquipmentName, outputVariable));
            return (nameSensor);
        }

        public string CreateActuator(IdfReader idf, string pumpName, string pumpType)
        {
            string nameActuator = "Control_On_Off_" + pumpName.Replace(" ", "");
            string actuator = @"EnergyManagementSystem:Actuator,
{0},
{1},
Plant Component {2},
On/Off Supervisory;";
            idf.Load(String.Format(actuator, nameActuator, pumpName, pumpType));
            return (nameActuator);
        }
        public string GetOutputVariable(string plantEquipmentType)
        {
            if (plantEquipmentType.Contains("Boiler"))
            {
                return "Boiler Heating Rate";
            }
            else if (plantEquipmentType.Contains("Chiller"))
            {
                return "Chiller Evaporator Cooling Rate";
            }
            else if (plantEquipmentType.Contains("HeatPump"))
            {
                return "Heat Pump Electricity Rate";
            }
            else if (plantEquipmentType.Contains("Tower"))
            {
                return "Cooling Tower Heat Transfer Rate";
            }
            else
            {
                throw new Exception(plantEquipmentType + " is not in the script's database.");
            }
        }
    }
}
